/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-05-23 23:41:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.annotation.WebServlet;
import java.sql.*;

public final class ok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\" xml:lang=\"fr\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("    <head>\r\n");
      out.write("      <!--Content-type-->\r\n");
      out.write("      <meta name='Content-Type' content='text/html'/>\r\n");
      out.write("       <meta charset='utf-8'/>\r\n");
      out.write("         \r\n");
      out.write("          <!--css style-->\r\n");
      out.write("          <!-- pour les mettre l'un a cote de l'autre-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/ui.css\"/>\r\n");
      out.write("\r\n");
      out.write("        <title>Erasmus </title>\r\n");
      out.write(" \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

		try{
			Class.forName("org.postgresql.Driver");  
			String url = "jdbc:postgresql://localhost/postgres";
			Connection con=DriverManager.getConnection(url,"postgres","root");

			String mail = request.getParameter("mail");
			

			Statement stmt = con.createStatement();
			String query = "select * from client where email='"+mail+"';";
	
			ResultSet rs = stmt.executeQuery(query);

				while (rs.next()) 
				{
					 String lastname = rs.getString(1); // lastname
					 String firstname = rs.getString(2); // firstname
					 String country = rs.getString(3); // country
					 String email = rs.getString(4); // email
					 String passwd = rs.getString(5); // passwd
		   

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img src=\"../img/man.png\" style=\"width:100px;height:100px;border: 1px solid #8293B2; margin-left: 80%\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:400px;height:350px;border:1px solid #8293B2;margin-left: 70%\"> <a href=\"../\"><img src=\"../img/para.jpg\" style=\"width:30px;height:30px;margin-top: 0%; margin-left: 90%\"></a> <b>LastName:</b><br> ");
 out.println(lastname); 
      out.write(" <br> <br><b> FirstName:</b>  <br>");
 out.println(firstname); 
      out.write("<br><br> <b> Country:</b><br>");
 out.println(country); 
      out.write("<br><br> <b>Email:</b> <br>");
 out.println(email); 
      out.write("<br><br> <b>PassWord:</b> <br>******* </div>\r\n");
      out.write("\r\n");

}
			con.close();
		}
		catch(Exception e){
			//out.println(e.getMessage());
		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-top: -27%;border:1px solid #8293B2;width:942px; \">\r\n");
      out.write("\r\n");
      out.write("<div style=\"border:1px solid #8293B2;width:220px;\" >\r\n");
      out.write("<h3>You can find a student </h3>\r\n");
      out.write("     <form class=\"form-horizontal\" action=\"../test\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label class=\"control-label col-sm-2\" for=\"email\">Search a Student:</label>\r\n");
      out.write("    <div class=\"col-sm-10\">\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"search\"  name=\"search\" placeholder=\"search a student\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"border:1px solid #8293B2;width:220px;\" >\r\n");
      out.write("<h3>You can find an University</h3>\r\n");
      out.write("     <form class=\"form-horizontal\"  action=\"../test\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label class=\"control-label col-sm-2\" for=\"email\">Search a University:</label>\r\n");
      out.write("    <div class=\"col-sm-10\">\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"university\"  name=\"university\" placeholder=\"search a University\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"border:1px solid #8293B2;width:220px;\" >\r\n");
      out.write("<h3>You can find a Job</h3>\r\n");
      out.write("     <form class=\"form-horizontal\"  action=\"../test\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label class=\"control-label col-sm-2\" for=\"email\">Search a Job:</label>\r\n");
      out.write("    <div class=\"col-sm-10\">\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"job\"  name=\"job\" placeholder=\"search a Job\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
